local L = AceLibrary("AceLocale-2.2"):new("XLoot")

L:RegisterTranslations("zhCN", function() 
	return {
		catSnap = "框体吸附设置",
		catLoot = "物品拾取设置",
		catFrame = "框体设置",
		catInfo = "拾取信息",
		catGeneralAppearance = "一般表现",
		catFrameAppearance = "框体表现",
		catLootAppearance = "拾取物品表现",
		catExtras = "额外",
		
		["2.0 compatability"] = "wow2.0修复",
		["If you're getting errors with table.setn, enable this"] = "出现table.setn报错时,勾选此项",
			
		optLock = "锁定",
		optOptions = "设置界面",
		optBehavior = "行为设置",
		optCursor = "吸附鼠标",
		optSmartsnap = "快速吸附",
		optSnapoffset = "吸附后鼠标偏移坐标值",
		optCollapse = "Collapse loot buttons",
		optDragborder = "可移动边框",
		optLootexpand = "Fit frame width to loot names",
		optAltoptions = "当Alt+RightClick显示菜单",
		optSwiftloot = "当Shift-拾取时不显示",
		optQualitytext = "显示物品品质",
		optInfotext = "显示物品信息",
		optLinkAll = "显示所有的链接按钮",
		optLinkAllVis = "可见: ",
		optLinkAllThreshold = "链接高于定义等级的物品",
		optLinkAllChannels = "总是链接到...",
		optAppearance = "外观",
		optQualityborder = "边框着色",
		optQualityframe = "背景着色",
		optLootqualityborder = "内边框着色",
		optBgcolor = "整体背景着色",
		optBordercolor = "整体边框着色",
		optTexColor = "物品图标着色",
		optHighlightLoot = "高亮拾取",
		optHighlightThreshold = "高亮条件设置", 
		optLootbgcolor = "拾取框背景着色",
		optLootbordercolor = "拾取框边框着色",
		optInfoColor = "信息文本颜色",
		optScale = "缩放",
		optAdvanced = "高级选项",
		optDebug = "Debug Messages",
		optDefaults = "恢复默认",
		
		descLock = "锁定拾取框",
		descOptions = "显示设置",
		descBehavior = "功能设置",
		descCursor = "拾取物品时，自动移动拾取框到鼠标位置",
		descSmartsnap = "当列表在您拾取物品时发生移动时，仅将拾取框垂直捕捉到光标，这样它就不会四处跳跃",
		descSnapoffset = "设置从要捕捉的第一个战利品图标中间水平方向的距离",
		descCollapse = "折叠战利品（空）按钮，如果光标选项已启用，则将光标放置在下一帧上。",
		descDragborder = "允许通过拖动框架的边框来移动拾取窗口，而不仅仅是按钮，否则可以点击按钮",
		descLootexpand = "更改帧宽度以匹配战利品名称。短的名字意味着窄的框架，长的名字使框架变宽",
		descAltoptions = "允许你按住Alt键并右键点击战利品，打开XLoot菜单。可以禁用，以避免与其他MOD发生冲突。",
		descSwiftloot = "尝试识别是否快速拾取，如果是则不会显示框架。如果遇到问题，应禁用。",
		descQualitytext = "在物品名称上方显示另一行，显示物品的质量",
		descInfotext = "在物品名称下方显示物品信息",
		descLinkAll = "链接所有按钮，一个弹出所有可用频道菜单的按钮，让你将当前打开的战利品发送给任何一个频道。",
		descLinkAllVis = "当“链接所有”按钮应可见时",
		descLinkAllThreshold = "仅链接高于阈值的物品",
		descLinkAllChannels = "左键单击“全部链接”时始终链接到这些频道。 |cFFFF0000如果未选中任何选项，左键单击“全部链接”将显示“全部链接”菜单。|r",
		descAppearance = "拾取框和每个单独的拾取按钮的着色、缩放和蒙皮",
		descQualityborder = "按最高质量的物品选择边框颜色",
		descQualityframe = "以最高质量的物品为背景色添加颜色",
		descLootqualityborder = "以品质颜色着色拾取边框",
		descHighlightLoot = "按品质颜色突出显示每个战利品框架",
		descHighlightThreshold = "The minimum quality at which loot frames will be highlighted",
		descBgcolor = "更改战利品框架本身的背景色",
		descBordercolor = "更改边框本身的边框颜色",
		descTexColor = "按品质为物品图标/纹理的边框上色",
		descLootbgcolor = "更改每个战利品的背景色",
		descLootbordercolor = "更改每个战利品的边框颜色",
		descInfoColor = "更改信息文本的颜色",
		descScale = "拾取框缩放",
		descAdvanced = "Options you may not want to mess with, but can anyway.",
		descDebug = "显示调试消息",
		descDefaults = "恢复XLoot附带的数据库，并将所有选项设置回默认值",
		
		qualityQuest = "任务物品",
		
		guiTitle = "XLoot设置",
		
		itemWeapon = "武器",
		
		evHerbs = "草药采集",
		evOpenNT = "打开 - No Text",
		evOpen = "打开",
		
		linkallloot = "链接...",
		linkallchanneldesc = "左键单击“全部链接”时自动将战利品链接到%s",
		}
end)